language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e3867d088cb4faeab487
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_success:
  - mvn clean cobertura:cobertura coveralls:report